# Generated by Django 5.1 on 2025-08-23 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0002_fundraiser_owner_pledge_supporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='anonymous',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
